[workspace]
preview = ["pixi-build"]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
name = "blade"
description = "Geometric Algebra."
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"
license = "MIT"

[tasks]
stable = "bash scripts/bump.sh stable"
nightly = "bash scripts/bump.sh nightly"
format = "mojo format -l 100 src"
build = "mojo precompile src -o .pixi/envs/default/lib/mojo/blade.mojoc"
temp = {cmd = "mojo .test.mojo", depends-on = ["build"] }
test = {cmd = "bash scripts/test.sh", depends-on = ["build"] }
cayley = {cmd = "mojo examples/cayley.mojo", depends-on = ["build"] }

# For testing and running examples,
# you could make a test environment instead,
# and use default-environment in tasks,
# but the lsp may not find the package.
#
# [tasks]
# test = {cmd = "bash scripts/test.sh", default-environment = "test" }
#
# [environments]
# test = ["test"]
#
# [feature.test.dependencies]
# blade = { path = "." }

[dependencies]
mojo = "==1.0.0b3.dev2026073014"

[package]
name = "blade"
version = "0.1.0"

[package.build.backend]
name="pixi-build-mojo"
version = "0.1.*"

[package.host-dependencies]
mojo = "==1.0.0b3.dev2026073014"

[package.build-dependencies]
mojo = "==1.0.0b3.dev2026073014"

[package.run-dependencies]
mojo = "==1.0.0b3.dev2026073014"
